(function(){
  const root=document.getElementById('feProbabili');if(!root)return;
  const safe=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const last=s=>{const a=String(s||'').trim().split(/\s+/).filter(Boolean);if(a.length>1&&/^[A-ZÀ-ÖØ-Ý]\.$/i.test(a.at(-1)))return a.at(-2);return a.length>1?a.at(-1):a[0]||''};let data=null,selected=0,side='home',loading=false;
  function when(d){if(!d)return'Orario da definire';try{return new Intl.DateTimeFormat('it-IT',{weekday:'short',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(d))}catch{return''}}
  function player(p){return `<div class="prob-player" tabindex="0" role="button" data-player-source-id="${safe(p.sourceId)}" data-player-name="${safe(p.name)}" data-player-club="${safe(p.club)}" data-player-image="${safe(p.image)}" data-player-profile-url="${safe(p.profileUrl)}" aria-label="Apri scheda di ${safe(p.name)}"><div class="prob-face">${p.image?`<img src="${safe(p.image)}" alt="${safe(p.name)}" loading="lazy" referrerpolicy="no-referrer" onerror="this.remove()">`:''}<span>${safe(p.name?.[0]||'?')}</span></div><div class="prob-label"><span class="prob-name">${safe(last(p.name))}</span><b class="prob-pct">${safe(p.probability)}%</b></div><div class="prob-probbar"><i style="width:${Math.max(3,Math.min(100,p.probability))}%"></i></div></div>`}
  function pitch(team){const lines=[...(team.lines||[])].reverse(),n=lines.length,start=n>=5?9:11,span=n>=5?82:74;return `<div class="prob-stadium prob-lines-${n}"><div class="prob-ad"><span>FANTA ELEVEN</span><span>FANTA ELEVEN</span><span>FANTA ELEVEN</span></div><div class="prob-pitch"><div class="prob-center-circle"></div><div class="prob-center-dot"></div><div class="prob-box prob-box-top"></div><div class="prob-box prob-box-bottom"></div><div class="prob-goal prob-goal-top"></div><div class="prob-goal prob-goal-bottom"></div>${lines.map((line,i)=>`<div class="prob-line prob-row-${i} prob-count-${line.length}" style="top:${n<=1?50:start+i*(span/(n-1))}%">${line.map(player).join('')}</div>`).join('')}</div><div class="prob-ad"><span>FANTA ELEVEN</span><span>FANTA ELEVEN</span><span>FANTA ELEVEN</span></div></div>`}
  function ballots(team){const rows=(team.players||[]).filter(p=>p.status==='Ballottaggio').map(p=>`<div class="prob-ballot"><b>${safe(p.name)}</b><span>${p.probability}% · ballottaggio</span></div>`);return rows.length?`<div class="prob-ballots"><h4>Ballottaggi</h4>${rows.join('')}</div>`:''}
  function render(){if(!data){root.innerHTML='<div class="prob-empty"><b>Caricamento probabili formazioni…</b><span>Confronto delle fonti in corso.</span></div>';return}if(!data.matches?.length){root.innerHTML='<div class="prob-empty"><b>Probabili non disponibili</b><span>Le fonti non hanno ancora pubblicato la prossima giornata.</span></div>';return}selected=Math.min(selected,data.matches.length-1);const m=data.matches[selected],team=side==='home'?m.homeTeam:m.awayTeam,updated=new Intl.DateTimeFormat('it-IT',{hour:'2-digit',minute:'2-digit'}).format(new Date(data.generatedAt));root.innerHTML=`<div class="prob-shell"><div class="prob-head"><div><h2>Probabili formazioni</h2><p>Giornata ${safe(data.matchday||'—')} · consenso multi-fonte</p></div><small>Aggiornato<br>${safe(updated)}</small></div><div class="prob-matches">${data.matches.map((x,i)=>`<button class="prob-match ${i===selected?'on':''}" data-prob-match="${i}"><b>${safe(x.home)} – ${safe(x.away)}</b><span>${safe(when(x.date))}</span></button>`).join('')}</div><div class="prob-card"><div class="prob-versus"><div><h3>${safe(m.home)} – ${safe(m.away)}</h3><p>${safe(when(m.date))}</p></div><div class="prob-coverage"><b>${m.coverage}/5</b><small>fonti rilevate</small></div></div><div class="prob-team-tabs"><button class="${side==='home'?'on':''}" data-prob-side="home">${safe(m.home)}<small>${safe(m.homeTeam.formation)}</small></button><button class="${side==='away'?'on':''}" data-prob-side="away">${safe(m.away)}<small>${safe(m.awayTeam.formation)}</small></button></div>${pitch(team)}${ballots(team)}</div></div>`;root.querySelectorAll('[data-prob-match]').forEach(b=>b.onclick=()=>{selected=+b.dataset.probMatch;side='home';render()});root.querySelectorAll('[data-prob-side]').forEach(b=>b.onclick=()=>{side=b.dataset.probSide;render()})}
  async function load(){if(loading||data)return;loading=true;render();try{const r=await fetch('/api/lineups',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error);data=d}catch(e){data={matches:[],error:e.message}}finally{loading=false;render()}}
  document.querySelectorAll('[data-t="probabili"]').forEach(b=>b.addEventListener('click',load));window.feLoadProbabili=load;
})();
