const {norm,clamp,aliases,text,lines}=require('./common');
const SOURCES=[
  ['Fantacalcio.it','https://www.fantacalcio.it/probabili-formazioni-serie-a',1],
  ['Sky Sport','https://sport.sky.it/calcio/serie-a/probabili-formazioni',.98],
  ['SOS Fanta','https://www.sosfanta.com/lista-formazioni/probabili-formazioni-serie-a/',.95],
  ['Sport Mediaset','https://www.sportmediaset.mediaset.it/probabili-formazioni/serie-a/',.94],
  ['Gazzetta','https://www.gazzetta.it/Calcio/prob_form/',.92],
  ['DAZN','https://www.dazn.com/it-IT/news/calcio/probabili-formazioni-serie-a-2026-27-titolari-moduli-e-ballottaggi-di-tutte-le-squadre/sxqiznnb92qk1ugq242gra6tp',.78],
  ['Goal','https://www.goal.com/it/liste/calciomercato-serie-a-2026-2027-acquisti-e-cessioni-trasferimenti-ufficiali-e-probabili-formazioni-tipo/bltf076d7afa9eb1393',.72]
];
const NEWS_WEIGHT={'fantacalcio.it':1,'sport.sky.it':.98,'sosfanta.com':.95,'sportmediaset.mediaset.it':.94,'gazzetta.it':.92,'dazn.com':.86,'goal.com':.8,'tuttomercatoweb.com':.78,'calciomercato.com':.75,'gianlucadimarzio.com':.8};
const MATCHDAY_SOURCES=new Set(['Fantacalcio.it','Sky Sport','SOS Fanta','Sport Mediaset','Gazzetta']);
function playerIndexes(ls,p){const a=aliases(p.name),out=[];for(let i=0;i<ls.length;i++)if(a.some(x=>norm(ls[i]).includes(x)))out.push(i);return out}
function pctNearPlayer(ls,i){for(let j=Math.max(0,i-1);j<=Math.min(ls.length-1,i+1);j++){const line=ls[j],ms=[...line.matchAll(/(\d{1,3})\s*%/g)].map(m=>+m[1]).filter(v=>v<=100);if(ms.length&&(j===i||/ballottaggio|favorit|titol|panchina|riserv|probabil/i.test(line)))return ms[0]}return null}
function parseSignal(ls,i){const z=ls.slice(Math.max(0,i-7),i+8).join(' '),pct=pctNearPlayer(ls,i),explicit=/indisponibile|forfait|non convocato|squalificato|\bout\b/i.test(z);if(explicit)return{probability:3,explicit:true,origin:'inferred',raw:'indisponibilità esplicita rilevata'};if(pct!=null)return{probability:clamp(pct,2,98),explicit:false,origin:'published',raw:`percentuale pubblicata ${pct}%`};if(/titolare|dal primo|dall['’]inizio|nell['’]undici/i.test(z))return{probability:88,explicit:false,origin:'inferred',raw:'Fanta Eleven: indicazione da titolare'};if(/panchina|riserva/i.test(z))return{probability:18,explicit:false,origin:'inferred',raw:'Fanta Eleven: indicazione da panchina'};if(/in dubbio|ballottaggio|da valutare/i.test(z))return{probability:50,explicit:false,origin:'inferred',raw:'Fanta Eleven: ballottaggio rilevato'};return null}
function aligned(ls,i,p,ctx,source){if(MATCHDAY_SOURCES.has(source[0]))return true;const opp=norm(ctx?.next?.opponent||''),club=norm(p.club||'');if(!opp||!club)return false;const z=norm(ls.slice(Math.max(0,i-18),i+19).join(' '));return z.includes(opp)&&z.includes(club)}
function signalRank(sig){if(!sig)return 0;if(sig.explicit&&sig.probability<=8)return 5;if(sig.origin==='published')return 4;if(sig.probability<=20||sig.probability>=80)return 3;return 2}
function direct(html,source,p,ctx){if(!html)return null;const ls=lines(html),idxs=playerIndexes(ls,p);if(!idxs.length)return null;const alignedIdxs=idxs.filter(i=>aligned(ls,i,p,ctx,source));if(!alignedIdxs.length){const sig=parseSignal(ls,idxs[0]);if(!sig)return null;return{source:source[0],url:source[1],probability:sig.probability,weight:source[2],reason:sig.raw,explicit:sig.explicit,origin:sig.origin,kind:'formazione',used:false,matchAligned:false,exclusionReason:'Fonte non verificata sulla prossima partita'}}let candidates=alignedIdxs.map(i=>parseSignal(ls,i)).filter(Boolean).sort((a,b)=>signalRank(b)-signalRank(a));if(MATCHDAY_SOURCES.has(source[0]))candidates=candidates.filter(x=>x.origin==='published'||x.explicit);const sig=candidates[0]||(MATCHDAY_SOURCES.has(source[0])?{probability:88,explicit:false,origin:'inferred',raw:'presente nella probabile formazione'}:null);return sig?{source:source[0],url:source[1],probability:sig.probability,weight:source[2],reason:sig.raw,explicit:sig.explicit,origin:sig.origin,kind:'formazione',used:true,matchAligned:true,exclusionReason:''}:null}
function tag(block,name){const m=block.match(new RegExp(`<${name}[^>]*>([\\s\\S]*?)<\\/${name}>`,'i'));return m?m[1].replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/\s+/g,' ').trim():''}
function host(u){try{return new URL(u).hostname.replace(/^www\./,'')}catch{return'altra fonte'}}
async function newsItems(p,ctx){const q=[`"${p.name}"`,p.club,ctx?.next?.opponent||'','(titolare OR ballottaggio OR panchina OR indisponibile OR infortunio OR squalificato)','when:7d'].filter(Boolean).join(' '),xml=await text(`https://news.google.com/rss/search?q=${encodeURIComponent(q)}&hl=it&gl=IT&ceid=IT:it`,6500),blocks=xml.match(/<item>[\s\S]*?<\/item>/gi)||[];return blocks.slice(0,18).map(b=>{const sm=b.match(/<source[^>]*url=["']([^"']+)/i);return{title:tag(b,'title'),description:tag(b,'description'),url:tag(b,'link'),date:tag(b,'pubDate'),source:host(sm?.[1]||tag(b,'link'))}})}
function classifyNews(item,p,ctx){const z=`${item.title} ${item.description}`,n=norm(z);if(!aliases(p.name).some(a=>n.includes(a)))return null;let s=0,r=[],persistent=false,explicit=false;if(/titolare|dal primo minuto|nell['’]undici|partir[àa] dall['’]inizio/i.test(z)){s+=1;r.push('indicato titolare')}if(/favorito|in vantaggio/i.test(z)){s+=.65;r.push('favorito')}if(/panchina|dalla panchina|non dovrebbe partire/i.test(z)){s-=.75;r.push('prevista panchina')}if(/in dubbio|da valutare|problema fisico|acciaccato/i.test(z)){s-=.4;r.push('condizione incerta');persistent=true}if(/infortun|lesion|forfait|non convocato|indisponibile/i.test(z)){s-=1;r.push('indisponibilità/condizione fisica');persistent=true;explicit=true}if(/squalificat/i.test(z)){s-=1;r.push('squalifica');persistent=true;explicit=true}s=clamp(s,-1,1);if(Math.abs(s)<.08)return null;const age=(Date.now()-Date.parse(item.date||''))/36e5,fresh=!isFinite(age)?.45:age<=18?1:age<=48?.82:age<=96?.6:.4,opp=norm(ctx?.next?.opponent||''),mentionsOpponent=!!opp&&n.includes(opp),prevTs=ctx?.previous?.date?Date.parse(ctx.previous.date):null,pubTs=Date.parse(item.date||''),afterPrevious=!prevTs||!isFinite(pubTs)||pubTs>prevTs,used=mentionsOpponent||(persistent&&fresh>=.6&&afterPrevious),w=(NEWS_WEIGHT[item.source]||.55)*fresh*(mentionsOpponent?.48:persistent?.28:.14);return{source:item.source,url:item.url,title:item.title,date:item.date,probability:Math.round(50+s*43),weight:w,reason:[...new Set(r)].join(' · '),explicit,kind:'news',used,matchAligned:mentionsOpponent,exclusionReason:used?'':'Notizia non riferita esplicitamente alla prossima gara'}}
async function loadSourceHtml(){return Promise.all(SOURCES.map(s=>text(s[1],14000)))}
function directSignals(html,p,ctx){return SOURCES.map((s,k)=>direct(html[k],s,p,ctx)).filter(Boolean)}
module.exports={loadSourceHtml,directSignals,newsItems,classifyNews};
