const {norm,clamp,aliases,text,json,lines,slug}=require('./common');

async function fixtures(){
  const a=new Date(Date.now()-150*864e5),b=new Date(Date.now()+42*864e5),f=x=>`${x.getUTCFullYear()}${String(x.getUTCMonth()+1).padStart(2,'0')}${String(x.getUTCDate()).padStart(2,'0')}`;
  try{const r=await fetch(`https://site.api.espn.com/apis/site/v2/sports/soccer/ita.1/scoreboard?dates=${f(a)}-${f(b)}&limit=200`),j=await r.json();return(j.events||[]).sort((x,y)=>new Date(x.date)-new Date(y.date))}catch{return[]}
}
function teamMatch(comp,club){const t=norm(club),cs=comp?.competitions?.[0]?.competitors||[],i=cs.findIndex(c=>[c?.team?.displayName,c?.team?.shortDisplayName,c?.team?.name].filter(Boolean).map(norm).some(n=>n===t||n.includes(t)||t.includes(n)));if(i<0)return null;const me=cs[i],other=cs.find((_,j)=>j!==i);return{id:comp.id||'',opponent:other?.team?.displayName||'Avversario',date:comp.date,homeAway:me?.homeAway==='home'?'Casa':'Trasferta'}}
function seasonStartTs(now=new Date()){const y=now.getUTCMonth()>=6?now.getUTCFullYear():now.getUTCFullYear()-1;return Date.UTC(y,6,1)}
function context(events,club){const matched=events.map(e=>teamMatch(e,club)).filter(Boolean),now=Date.now(),cut=seasonStartTs(new Date(now)),prevs=matched.filter(x=>{const t=new Date(x.date).getTime();return t<now-2*36e5&&t>=cut}).sort((a,b)=>new Date(b.date)-new Date(a.date)),next=matched.filter(x=>new Date(x.date)>=now-2*36e5).sort((a,b)=>new Date(a.date)-new Date(b.date))[0]||null;return{previous:prevs[0]||null,previousMatches:prevs.slice(0,5),next}}

function hitFactory(name){const aa=aliases(name);return s=>{const n=norm(s);return aa.some(a=>n===a||n.includes(a)||a.includes(n))}}
function starterFromSummary(root,name){const hit=hitFactory(name);let state=null;function walk(x,d=0){if(!x||d>14)return;if(Array.isArray(x)){for(const v of x)walk(v,d+1);return}if(typeof x!=='object')return;const person=x.athlete||x.player||x.person||null;const names=[person?.displayName,person?.fullName,person?.shortName,person?.name,x.displayName,x.fullName,x.shortName,x.name].filter(Boolean);if(names.some(hit)){for(const k of ['starter','didStart','starting','isStarter'])if(typeof x[k]==='boolean')state={found:true,starter:x[k],via:k};if(typeof person?.starter==='boolean')state={found:true,starter:person.starter,via:'person.starter'}}for(const[k,v]of Object.entries(x)){if(k==='links'||k==='headshot')continue;walk(v,d+1)}}walk(root);return state||{found:false,starter:null}}
function minuteOf(o){const vals=[o?.clock?.displayValue,o?.clock?.value,o?.time?.displayValue,o?.time,o?.minute,o?.minutes,o?.displayClock];for(const v of vals){if(v==null)continue;const m=String(v).match(/(\d{1,3})/);if(m)return +m[1]}return null}
function textsOf(o){const vals=[o?.text,o?.shortText,o?.detail,o?.description,o?.headline,o?.type?.text,o?.type?.description,o?.play?.text];return vals.filter(v=>typeof v==='string'&&v.length>0)}
function substitutionFromSummary(root,name){const hit=hitFactory(name);let entry=null,exit=null;function scanText(text,minute){const t=String(text||'').replace(/\s+/g,' ').trim();if(!t||minute==null)return;let m=t.match(/(.+?)\s+replaces\s+(.+?)(?:[.!]|$)/i);if(m){if(hit(m[1]))entry=minute;if(hit(m[2]))exit=minute}m=t.match(/sostituzione[^.]*?([A-Za-zÀ-ÿ.' -]+?)\s+(?:prende il posto di|al posto di)\s+([A-Za-zÀ-ÿ.' -]+?)(?:[.!]|$)/i);if(m){if(hit(m[1]))entry=minute;if(hit(m[2]))exit=minute}}
 function walk(x,d=0){if(!x||d>14)return;if(Array.isArray(x)){for(const v of x)walk(v,d+1);return}if(typeof x!=='object')return;const minute=minuteOf(x);for(const t of textsOf(x))scanText(t,minute);for(const[k,v]of Object.entries(x)){if(k==='links'||k==='headshot')continue;walk(v,d+1)}}walk(root);return{entry,exit}}
function rosterStarter(summary,name){const hit=hitFactory(name);for(const team of summary?.rosters||[])for(const row of team?.roster||[]){const a=row?.athlete||{},names=[a.displayName,a.fullName,a.shortName,a.name].filter(Boolean);if(names.some(hit)&&typeof row.starter==='boolean')return{found:true,starter:row.starter,via:'roster'}}return{found:false,starter:null}}
function deriveAppearance(summary,p,m){const roster=rosterStarter(summary,p.name),st=roster.found?roster:starterFromSummary(summary,p.name),sub=substitutionFromSummary(summary,p.name);let starter=st.starter;if(starter==null){starter=sub.entry==null&&sub.exit!=null?true:sub.entry!=null?false:null}if(starter==null)return null;let minutes;if(starter===true)minutes=clamp(sub.exit??90,0,90);else minutes=sub.entry==null?0:clamp((sub.exit??90)-sub.entry,0,90);return{starter,entry:sub.entry,exit:sub.exit,minutes,opponent:m.opponent,date:m.date,homeAway:m.homeAway}}

const LIST_URLS=['https://raw.githubusercontent.com/bqit/fantaleghe-api-json/refs/heads/main/players.json','https://cdn.jsdelivr.net/gh/bqit/fantaleghe-api-json@main/players.json'];let listCache=null,listCacheAt=0;const roleMap={P:'POR',D:'DIF',C:'CEN',A:'ATT'};
async function catalogPlayers(){if(listCache&&Date.now()-listCacheAt<6*36e5)return listCache;for(const u of LIST_URLS){const j=await json(u,6500);if(Array.isArray(j)&&j.length>300){listCache=j.map(x=>({sourceId:String(x.id),name:String(x.name||''),club:String(x.team||''),role:roleMap[x.position]||''})).filter(x=>x.sourceId&&x.name&&x.club);listCacheAt=Date.now();return listCache}}return[]}
async function resolvePlayer(p){if(p.sourceId)return{sourceId:String(p.sourceId),name:p.name,club:p.club,role:p.role};const all=await catalogPlayers(),club=norm(p.club),aa=aliases(p.name);let best=null,score=-1;for(const x of all){if(norm(x.club)!==club)continue;const n=norm(x.name),last=n.split(' ').at(-1)||'',s=aa.some(a=>n===a)?100:aa.some(a=>last===a)?98:aa.some(a=>n.includes(a)||a.includes(n))?80:0;if(s>score){best=x;score=s}}return score>=80?best:null}
async function seasonBaseline(p){const x=await resolvePlayer(p);if(!x)return null;const url=`https://www.fantacalcio.it/serie-a/squadre/${slug(p.club)}/${slug(x.name||p.name)}/${encodeURIComponent(x.sourceId)}/2026-27`,h=await text(url,7000);if(!h)return null;const plain=lines(h).join(' '),ms=plain.match(/Titolare\s+(\d+)\s*-\s*(\d{1,3})\s*%/i),me=plain.match(/Entrato\s+(\d+)\s*-\s*(\d{1,3})\s*%/i),mu=plain.match(/Inutilizzato\s+(\d+)\s*-\s*(\d{1,3})\s*%/i);if(!ms)return null;const starts=+ms[1],published=clamp(+ms[2],0,100),subs=me?+me[1]:0,unused=mu?+mu[1]:0;let games=starts+subs+unused;if(games<1){const mv=plain.match(/Partite a voto\s*\|?\s*(\d+)/i);games=mv?+mv[1]:0}if(games<1)return null;const shrink=games>=8?.86:games>=5?.72:games>=3?.58:games===2?.42:.25,probability=Math.round(50+(published-50)*shrink);return{source:'Fantacalcio.it · riepilogo stagione',url,probability:clamp(probability,12,88),publishedProbability:published,weight:.62,reason:`Riepilogo stagione: ${starts}/${games} titolarità (${published}% pubblicato)`,kind:'history',used:true,games,starts}}
const summaryCache=new Map();
async function espnSummary(eventId){const key=String(eventId),cached=summaryCache.get(key);if(cached&&Date.now()-cached.at<20*60e3)return cached.value;const u=`https://site.api.espn.com/apis/site/v2/sports/soccer/ita.1/summary?event=${encodeURIComponent(key)}`;const pending=(async()=>{let j=await json(u,14000);if(!j)j=await json(u,18000);return j})();summaryCache.set(key,{at:Date.now(),value:pending});const j=await pending;if(j)summaryCache.set(key,{at:Date.now(),value:j});else summaryCache.delete(key);return j}
async function recentBaseline(p,ctx){const matches=(ctx?.previousMatches||[]).filter(x=>x.id).slice(0,5);if(!matches.length)return null;const weights=[1,.86,.74,.64,.56];const rows=await Promise.all(matches.map(async(m,i)=>{const j=await espnSummary(m.id);const a=j?deriveAppearance(j,p,m):null;return a?{...a,w:weights[i]||.5}:null}));const valid=rows.filter(Boolean);if(valid.length<1)return null;let tw=0,startW=0,utilW=0,starts=0,totalMinutes=0;for(const r of valid){tw+=r.w;if(r.starter){startW+=r.w;starts++}utilW+=(r.minutes/90)*r.w;totalMinutes+=r.minutes}const startPct=tw?startW/tw*100:50,utilPct=tw?utilW/tw*100:50,raw=startPct*.78+utilPct*.22,shrink=valid.length>=5?.88:valid.length===4?.82:valid.length===3?.74:valid.length===2?.64:.40,probability=Math.round(50+(raw-50)*shrink),avgMinutes=Math.round(totalMinutes/valid.length);return{source:'ESPN JSON · ultime gare',url:'https://www.espn.com/soccer/',probability:clamp(probability,8,94),weight:.62,reason:`Ultime ${valid.length}: ${starts}/${valid.length} titolare · ${avgMinutes}' medi · recency pesata`,kind:'history',used:true,games:valid.length,starts,avgMinutes,matches:valid.map(r=>({opponent:r.opponent,date:r.date,homeAway:r.homeAway,starter:r.starter,minutes:r.minutes,entry:r.entry,exit:r.exit}))}}
async function historicalBaseline(p,ctx){const[season,recent]=await Promise.all([seasonBaseline(p),recentBaseline(p,ctx)]);if(!season&&!recent)return null;if(season&&recent){let probability,effectiveN;if(recent.games>=season.games&&season.games<=5){probability=recent.probability;effectiveN=Math.max(1,recent.games)}else{const rw=recent.games>=5?.72:recent.games===4?.68:recent.games===3?.64:.58;probability=Math.round(season.probability*(1-rw)+recent.probability*rw);effectiveN=Math.min(12,Math.max(season.games,recent.games)+Math.min(recent.games,5)*.2)}return{source:'Storico titolarità + minuti',url:season.url,probability:clamp(probability,8,94),weight:.72,reason:`${recent.reason}. Stagione ${season.starts}/${season.games} come cross-check.`,kind:'history',used:true,games:Math.max(season.games,recent.games),starts:recent.starts,effectiveN,season,recent}}const h=recent||season;return{...h,effectiveN:Math.min(10,Math.max(1,h.games||1)),season:season||null,recent:recent||null}}
module.exports={fixtures,context,historicalBaseline,deriveAppearance,recentBaseline};
