const {norm,aliases}=require('./common');
const {SOURCES}=require('./editorial');

const clean=s=>String(s||'').replace(/&#x([0-9a-f]+);/gi,(_,h)=>String.fromCodePoint(parseInt(h,16))).replace(/&#(\d+);/g,(_,d)=>String.fromCodePoint(parseInt(d,10))).replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();
function playerFrom(block,club){const a=block.match(/<a\b[^>]*class=["'][^"']*player-name[^"']*["'][^>]*href=["']([^"']*\/serie-a\/squadre\/([^\/"']+)\/([^\/"']+)\/(\d+)[^"']*)["'][\s\S]*?<span>([\s\S]*?)<\/span>[\s\S]*?<\/a>/i);if(!a)return null;const image=block.match(/<img[^>]*class=["'][^"']*player-image[^"']*["'][^>]*src=["']([^"']+)/i)?.[1]||`https://content.fantacalcio.it/web/campioncini/21/medium/${a[4]}.png?v=20260902`;return{sourceId:String(a[4]),name:clean(a[5]),club,clubSlug:a[2],image,profileUrl:a[1]}}
function parseTeam(section,side,club){const re=new RegExp(`<div\\s+class=["']team team-${side}["'][^>]*data-team-formation=["']([^"']+)["'][\\s\\S]*?<ul\\s+class=["']team-lineup["'][^>]*>([\\s\\S]*?)<\\/ul>`,'i'),m=section.match(re);if(!m)return{club,formation:'—',lines:[],players:[]};const chunks=m[2].split(/<li\s+class=["']separator["'][^>]*>[\s\S]*?<\/li>/i),lines=[];for(const chunk of chunks){const players=(chunk.match(/<li\b[^>]*class=["'][^"']*player[^"']*["'][\s\S]*?<\/li>/gi)||[]).map(x=>playerFrom(x,club)).filter(Boolean);if(players.length)lines.push(players)}return{club,formation:m[1],lines,players:lines.flat()}}
function parseBallots(section){const map=new Map(),blocks=section.match(/<ul\s+class=["']ballot-list["'][^>]*>[\s\S]*?<\/ul>/gi)||[];for(const block of blocks){for(const row of block.match(/<li\b[^>]*>[\s\S]*?<\/li>/gi)||[]){const p=playerFrom(row,''),pct=Number(row.match(/class=["']percentage["'][^>]*>\s*(\d{1,3})\s*%/i)?.[1]);if(p&&Number.isFinite(pct))map.set(p.sourceId,pct)}}return map}
function upcoming(events){const now=Date.now(),out=[];for(const e of events||[]){const t=Date.parse(e.date||'');if(!Number.isFinite(t)||t<now-3*36e5)continue;const cs=e?.competitions?.[0]?.competitors||[];if(cs.length!==2)continue;const home=cs.find(x=>x.homeAway==='home')||cs[0],away=cs.find(x=>x!==home)||cs[1],name=x=>x?.team?.displayName||x?.team?.shortDisplayName||x?.team?.name||'';out.push({home:name(home),away:name(away),date:e.date})}return out.sort((a,b)=>Date.parse(a.date)-Date.parse(b.date)).slice(0,10)}
function findKickoff(schedule,home,away){return schedule.find(x=>{const h=norm(home),a=norm(away),xh=norm(x.home),xa=norm(x.away);return(xh.includes(h)||h.includes(xh))&&(xa.includes(a)||a.includes(xa))})||null}
function present(text,p){const n=norm(text),club=norm(p.club);return aliases(p.name).some(a=>a.length>2&&n.includes(a))&&(!club||n.includes(club))}
function enrich(team,sourceTexts,ballots){const sourceDefs=SOURCES.slice(0,5);team.players.forEach(p=>{const found=[];sourceTexts.slice(0,5).forEach((t,i)=>{if(present(t,p))found.push(sourceDefs[i][0])});if(!found.includes('Fantacalcio.it'))found.unshift('Fantacalcio.it');const ballot=ballots.get(p.sourceId);p.probability=ballot??Math.min(94,70+found.length*5);p.sources=found;p.status=ballot!=null?'Ballottaggio':found.length>=4?'Molto probabile':found.length>=3?'Favorito':'Probabile'});team.lines=team.lines.map(line=>line.map(p=>team.players.find(x=>x.sourceId===p.sourceId)||p));return team}
function parseProbableLineups(html,sourceHtml=[],events=[]){const markers=[...String(html||'').matchAll(/<li\s+class=["'][^"']*match match-item[^"']*["'][^>]*id=["']match-(\d+)["'][^>]*>/gi)],schedule=upcoming(events),matches=[],sourceTexts=sourceHtml.map(clean);for(let i=0;i<markers.length;i++){const end=markers[i+1]?.index??html.length,section=html.slice(markers[i].index,end),pitchAt=section.indexOf('<div class="pitch">'),head=section.slice(0,pitchAt>0?pitchAt:5000),teams=[...head.matchAll(/<a\b[^>]*class=["'][^"']*team-name[^"']*["'][^>]*href=["']([^"']+)["'][\s\S]*?<meta\s+itemprop=["']name["']\s+content=["']([^"']+)["']/gi)].slice(0,2);if(teams.length<2)continue;const home=clean(teams[0][2]),away=clean(teams[1][2]),ballots=parseBallots(section),kick=findKickoff(schedule,home,away),homeTeam=enrich(parseTeam(section,'home',home),sourceTexts,ballots),awayTeam=enrich(parseTeam(section,'away',away),sourceTexts,ballots);if(homeTeam.players.length!==11||awayTeam.players.length!==11)continue;const sourceSet=new Set([...homeTeam.players,...awayTeam.players].flatMap(p=>p.sources));matches.push({id:String(markers[i][1]),home,away,date:kick?.date||'',homeTeam,awayTeam,sources:[...sourceSet],coverage:sourceSet.size})}return{matchday:Number(String(html).match(/class=["']matchweek["'][^>]*>\s*(\d+)/i)?.[1])||null,matches}}
module.exports={parseProbableLineups};
