const LIST_URLS=['https://raw.githubusercontent.com/bqit/fantaleghe-api-json/refs/heads/main/players.json','https://cdn.jsdelivr.net/gh/bqit/fantaleghe-api-json@main/players.json'];
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const slug=s=>norm(s).replace(/\s+/g,'-');
const roleMap={P:'POR',D:'DIF',C:'CEN',A:'ATT'};
let cache=null,cacheAt=0;
async function fetchJson(url,ms=6500){const c=new AbortController(),to=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{signal:c.signal,headers:{'user-agent':'Mozilla/5.0 FantaEleven/3.0'}});if(!r.ok)return null;return await r.json()}catch{return null}finally{clearTimeout(to)}}
async function load(){if(cache&&Date.now()-cacheAt<6*36e5)return cache;for(const u of LIST_URLS){const j=await fetchJson(u);if(Array.isArray(j)&&j.length>300){cache=j.map(p=>({id:String(p.id),name:String(p.name||''),club:String(p.team||''),role:roleMap[p.position]||'',image:p.playerImage||''})).filter(p=>p.name&&p.club&&p.role);cacheAt=Date.now();return cache}}return[]}
function score(p,q){const n=norm(p.name),qq=norm(q),parts=n.split(' '),last=parts.at(-1)||'';return n===qq?100:last===qq?99:last.startsWith(qq)?96:n.startsWith(qq)?93:n.includes(qq)?82:0}
function decode(s){return String(s||'').replace(/&amp;/g,'&').replace(/&#39;|&apos;/g,"'").replace(/&quot;/g,'"').replace(/&agrave;/g,'à').replace(/&egrave;/g,'è').replace(/&igrave;/g,'ì').replace(/&ograve;/g,'ò').replace(/&ugrave;/g,'ù').trim()}
async function fullName(p){const url=`https://www.fantacalcio.it/serie-a/squadre/${slug(p.club)}/${slug(p.name)}/${encodeURIComponent(p.id)}/2026-27`;const c=new AbortController(),to=setTimeout(()=>c.abort(),4500);try{const r=await fetch(url,{signal:c.signal,headers:{'user-agent':'Mozilla/5.0 FantaEleven/3.0','accept-language':'it-IT,it;q=.9'}});if(!r.ok)return p;const h=await r.text();let m=h.match(/<title>\s*([^<]+?)\s*-\s*Profilo calciatore/i)||h.match(/<h1[^>]*>\s*([^<]+?)\s*<\/h1>/i);const n=decode(m?.[1]);if(n&&norm(n)!==norm(p.name)&&n.length<70)return{...p,name:n,profileUrl:url};return{...p,profileUrl:url}}catch{return p}finally{clearTimeout(to)}}
module.exports=async(req,res)=>{res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Methods','GET, OPTIONS');if(req.method==='OPTIONS')return res.status(204).end();if(req.method!=='GET')return res.status(405).json({error:'Metodo non consentito'});const q=String(req.query?.q||'').trim();if(q.length<2)return res.status(200).json({players:[]});const all=await load();if(!all.length)return res.status(503).json({error:'Catalogo temporaneamente non disponibile'});const top=all.map(p=>({p,s:score(p,q)})).filter(x=>x.s).sort((a,b)=>b.s-a.s).slice(0,8).map(x=>x.p);const enriched=await Promise.all(top.map(fullName));res.setHeader('Cache-Control','public, s-maxage=21600, stale-while-revalidate=86400');return res.status(200).json({players:enriched,source:'listone+profili',count:enriched.length})};
